# @package _global_
defaults:
  - _self_

# ============================================================================
# Coronary Angiography Vessel Segmentation Training Config
# Based on ODinW13 config but with segmentation enabled
# ============================================================================

paths:
  angio_data_root: E:/AngioMLDL_data/coco_format_v2
  experiment_log_dir: C:/Users/odressler/AngioMLDL_SAM/experiments/phase1_vessel_seg
  bpe_path: C:/Users/odressler/sam3/assets/bpe_simple_vocab_16e6.txt.gz


angio_train:
  # Training transforms pipeline
  train_transforms:
    - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
      transforms:
        - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
          query_filter:
            _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
        - _target_: sam3.train.transforms.segmentation.DecodeRle
        - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
          sizes:
            _target_: sam3.train.transforms.basic.get_random_resize_scales
            size: ${scratch.resolution}
            min_size: 480
            rounded: false
          max_size:
            _target_: sam3.train.transforms.basic.get_random_resize_max_size
            size: ${scratch.resolution}
          square: true
          consistent_transform: ${scratch.consistent_transform}
        - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
          size: ${scratch.resolution}
          consistent_transform: ${scratch.consistent_transform}
        - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
        # Point prompts for better mask precision (bypasses text encoder)
        - _target_: sam3.train.transforms.point_sampling.RandomGeometricInputsAPI
          num_points: [5, 15]           # Sample 5-15 points per vessel
          box_chance: 0.2               # 20% include box prompt
          point_sample_mode: "centered" # Distance transform - finds centerline points
          box_noise_std: 0.1            # Noise for robustness
          geometric_query_str: "visual" # Bypass text encoder
          resample_box_from_mask: true  # Compute box from mask
        - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
          query_filter:
            _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
        - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
          mean: ${scratch.train_norm_mean}
          std: ${scratch.train_norm_std}
        - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
          query_filter:
            _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterFindQueriesWithTooManyOut
        max_num_objects: ${scratch.max_ann_per_img}

  # Validation transforms pipeline
  val_transforms:
    - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
      transforms:
        - _target_: sam3.train.transforms.segmentation.DecodeRle
        - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
          sizes: ${scratch.resolution}
          max_size:
            _target_: sam3.train.transforms.basic.get_random_resize_max_size
            size: ${scratch.resolution}
          square: true
          consistent_transform: False
        - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
        - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
          mean: ${scratch.val_norm_mean}
          std: ${scratch.val_norm_std}

  # Loss config WITH mask loss for segmentation
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher: ${scratch.matcher}
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: ${scratch.use_o2m_matcher_on_o2m_aux}
    loss_fns_find:
      - _target_: sam3.train.loss.loss_fns.Boxes
        weight_dict:
          loss_bbox: 5.0
          loss_giou: 2.0
      - _target_: sam3.train.loss.loss_fns.IABCEMdetr
        weak_loss: False
        weight_dict:
          loss_ce: ${scratch.loss_ce_weight}
          presence_loss: ${scratch.presence_weight}
        pos_weight: ${scratch.iabce_pos_weight}
        alpha: ${scratch.iabce_alpha}
        gamma: 2
        use_presence: True
        pos_focal: ${scratch.iabce_pos_focal}
        pad_n_queries: ${scratch.num_queries}
        pad_scale_pos: ${scratch.instance_query_loss_pad_scale_pos}
      # CRITICAL: Mask loss for segmentation
      - _target_: sam3.train.loss.loss_fns.Masks
        weight_dict:
          loss_mask: 5.0
          loss_dice: 5.0
    # Semantic segmentation loss - provides negative supervision (background vs vessel)
    loss_fn_semantic_seg:
      _target_: sam3.train.loss.loss_fns.SemanticSegCriterion
      weight_dict:
        loss_semantic_seg: 5.0
      focal: true
      focal_alpha: 0.6
      focal_gamma: 1.6
      downsample: true
      presence_head: false
      presence_loss: true
    scale_by_find_batch_size: ${scratch.scale_by_find_batch_size}


# ============================================================================
# Model and Training Parameters
# ============================================================================
scratch:
  # CRITICAL: Enable segmentation
  enable_segmentation: True

  use_act_checkpoint_geo_encoder: True
  input_geometry_encoder:
    _target_: sam3.model.geometry_encoders.SequenceGeometryEncoder
    pos_enc: ${scratch.pos_embed}
    encode_boxes_as_points: False
    points_direct_project: True
    points_pool: True
    points_pos_enc: True
    boxes_direct_project: True
    boxes_pool: True
    boxes_pos_enc: True
    d_model: ${scratch.d_model}
    num_layers: 3
    use_act_ckpt: ${scratch.use_act_checkpoint_geo_encoder}
    layer:
      _target_: sam3.model.encoder.TransformerEncoderLayer
      activation: "relu"
      d_model: ${scratch.d_model}
      dim_feedforward: 2048
      dropout: ${scratch.encoder_dropout}
      pos_enc_at_attn: false
      pre_norm: True
      pos_enc_at_cross_attn_queries: false
      pos_enc_at_cross_attn_keys: true
      self_attention:
        _target_: sam3.model.attention.MultiheadAttention
        attn_type: Vanilla
        num_heads: 8
        dropout: ${scratch.encoder_dropout}
        embed_dim: ${scratch.d_model}
        batch_first: False
      cross_attention:
        _target_: sam3.model.attention.MultiheadAttention
        attn_type: Vanilla
        num_heads: 8
        dropout: ${scratch.encoder_dropout}
        embed_dim: ${scratch.d_model}
        batch_first: False
    add_cls: true
    add_post_encode_proj: True

  boxRPB: "log"
  dac: True
  use_early_fusion: true
  o2m_mask: false
  num_feature_levels: 1
  encoder_dropout: 0.1
  decoder_dropout: 0.1

  tokenizer_ve:
    _target_: sam3.model.tokenizer_ve.SimpleTokenizer
    bpe_path: ${paths.bpe_path}

  freeze_text_tower: False
  freeze_image_tower: NoFreeze
  vis_backbone_dp: 0.0

  # Activation checkpointing (save memory)
  use_act_checkpoint_vision_backbone: True
  use_act_checkpoint_text_backbone: True
  use_act_checkpoint_encoder: True
  use_act_checkpoint_decoder: True

  loss: null

  # Loss parameters
  num_queries: 200
  presence_weight: 20.0
  loss_ce_weight: 20.0
  iabce_pos_weight: 5.0
  iabce_pos_focal: false
  iabce_alpha: 0.25
  instance_query_loss_pad_scale_pos: 1.0
  use_o2m_matcher_on_o2m_aux: false

  # Model parameters
  use_instance_query: true
  d_model: 256
  pos_embed:
    _target_: sam3.model.position_encoding.PositionEmbeddingSine
    num_pos_feats: ${scratch.d_model}
    normalize: true
    scale: null
    temperature: 10000

  # Box processing
  use_presence_eval: True
  original_box_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    iou_type: segm  # CRITICAL: Must be segm for segmentation evaluation
    use_original_ids: true
    use_original_sizes_box: true
    use_original_sizes_mask: true
    convert_mask_to_rle: true  # Convert masks to RLE for COCO eval
    use_presence: ${scratch.use_presence_eval}

  # Matcher configuration
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: False
  scale_by_find_batch_size: True

  # Image processing parameters
  resolution: 1008
  consistent_transform: False
  max_ann_per_img: 200

  # Normalization parameters
  train_norm_mean: [0.5, 0.5, 0.5]
  train_norm_std: [0.5, 0.5, 0.5]
  val_norm_mean: [0.5, 0.5, 0.5]
  val_norm_std: [0.5, 0.5, 0.5]

  # Training parameters - optimized for 2x RTX 3090
  train_batch_size: 2  # Per GPU, effective batch size = 4
  val_batch_size: 1
  num_train_workers: 4
  num_val_workers: 2
  max_data_epochs: 50
  target_epoch_size: 521  # All training samples
  hybrid_repeats: 1
  context_length: 2
  gather_pred_via_filesys: false

  # Learning rate and scheduler parameters
  # Reduced from 0.1 to 0.02 to prevent NaN - small dataset needs conservative LR
  lr_scale: 0.02
  lr_transformer: ${times:8e-4,${scratch.lr_scale}}
  lr_vision_backbone: ${times:2.5e-4,${scratch.lr_scale}}
  lr_language_backbone: ${times:5e-5,${scratch.lr_scale}}
  lrd_vision_backbone: 0.9
  wd: 0.1
  scheduler_timescale: 20
  scheduler_warmup: 20
  scheduler_cooldown: 20


# ============================================================================
# Trainer Configuration
# ============================================================================

trainer:
  _target_: sam3.train.trainer.Trainer
  skip_saving_ckpts: false  # Save checkpoints
  empty_gpu_mem_cache_after_eval: True
  skip_first_val: False
  max_epochs: ${scratch.max_data_epochs}
  accelerator: cuda
  seed_value: 42
  val_epoch_freq: 5

  distributed:
    backend: gloo  # Use gloo for Windows (NCCL not available)
    find_unused_parameters: True
    gradient_as_bucket_view: True
    static_graph: True  # Enables optimization for consistent unused params (semantic_seg_head)

  loss:
    all: ${angio_train.loss}
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss

  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        limit_ids: null
        transforms: ${angio_train.train_transforms}
        load_segmentation: ${scratch.enable_segmentation}
        max_ann_per_img: 500000
        multiplier: 1
        max_train_queries: 50000
        max_val_queries: 50000
        training: true
        use_caching: False
        img_folder: ${paths.angio_data_root}/train/images
        ann_file: ${paths.angio_data_root}/train/annotations.json
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          prompts: null  # Use category names from JSON
          include_negatives: true  # Include negative samples for background learning
          _partial_: true
      shuffle: True
      batch_size: ${scratch.train_batch_size}
      num_workers: ${scratch.num_train_workers}
      pin_memory: True
      drop_last: True
      collate_fn:
        _target_: sam3.train.data.collator.collate_fn_api
        _partial_: true
        repeats: ${scratch.hybrid_repeats}
        dict_key: all
        with_seg_masks: ${scratch.enable_segmentation}

    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: ${scratch.enable_segmentation}
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          prompts: null
          include_negatives: true  # Include negative samples for proper evaluation
          _partial_: true
        img_folder: ${paths.angio_data_root}/val/images
        ann_file: ${paths.angio_data_root}/val/annotations.json
        transforms: ${angio_train.val_transforms}
        max_ann_per_img: 100000
        multiplier: 1
        training: false
      shuffle: False
      batch_size: ${scratch.val_batch_size}
      num_workers: ${scratch.num_val_workers}
      pin_memory: True
      drop_last: False
      collate_fn:
        _target_: sam3.train.data.collator.collate_fn_api
        _partial_: true
        repeats: 1
        dict_key: angio
        with_seg_masks: ${scratch.enable_segmentation}

  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: ${paths.bpe_path}
    device: cpu  # Will be moved to GPU during training
    eval_mode: false
    enable_segmentation: ${scratch.enable_segmentation}

  meters:
    val:
      angio:
        detection:
          _target_: sam3.eval.coco_writer.PredictionDumper
          iou_type: "segm"  # Use segmentation IoU
          dump_dir: ${launcher.experiment_log_dir}/dumps/angio
          merge_predictions: True
          postprocessor: ${scratch.original_box_postprocessor}
          gather_pred_via_filesys: ${scratch.gather_pred_via_filesys}
          maxdets: 100
          pred_file_evaluators:
            - _target_: sam3.eval.coco_eval_offline.CocoEvaluatorOfflineWithPredFileEvaluators
              gt_path: ${paths.angio_data_root}/val/annotations.json
              tide: False
              iou_type: "segm"
              positive_split: False

  optim:
    amp:
      enabled: True
      amp_dtype: float16  # Changed from bfloat16 - gloo backend on Windows doesn't support bfloat16

    optimizer:
      _target_: torch.optim.AdamW

    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2

    param_group_modifiers:
      - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
        _partial_: True
        layer_decay_value: ${scratch.lrd_vision_backbone}
        apply_to: 'backbone.vision_backbone.trunk'
        overrides:
          - pattern: '*pos_embed*'
            value: 1.0

    options:
      lr:
        - scheduler:
            _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
            base_lr: ${scratch.lr_transformer}
            timescale: ${scratch.scheduler_timescale}
            warmup_steps: ${scratch.scheduler_warmup}
            cooldown_steps: ${scratch.scheduler_cooldown}
        - scheduler:
            _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
            base_lr: ${scratch.lr_vision_backbone}
            timescale: ${scratch.scheduler_timescale}
            warmup_steps: ${scratch.scheduler_warmup}
            cooldown_steps: ${scratch.scheduler_cooldown}
          param_names:
            - 'backbone.vision_backbone.*'
        - scheduler:
            _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
            base_lr: ${scratch.lr_language_backbone}
            timescale: ${scratch.scheduler_timescale}
            warmup_steps: ${scratch.scheduler_warmup}
            cooldown_steps: ${scratch.scheduler_cooldown}
          param_names:
            - 'backbone.language_backbone.*'

      weight_decay:
        - scheduler:
            _target_: fvcore.common.param_scheduler.ConstantParamScheduler
            value: ${scratch.wd}
        - scheduler:
            _target_: fvcore.common.param_scheduler.ConstantParamScheduler
            value: 0.0
          param_names:
            - '*bias*'
          module_cls_names: ['torch.nn.LayerNorm']

  checkpoint:
    save_dir: ${launcher.experiment_log_dir}/checkpoints
    save_freq: 10  # Save every 10 epochs
    # Resume from epoch 20 checkpoint (stable, before NaN crash at epoch 26)
    resume_from: null  # Start fresh
    # Save best model based on validation AP
    save_best_meters:
      - val_angio/detection/coco_eval_segm_AP  # Best overall segmentation AP
      - val_angio/detection/coco_eval_segm_AP_50  # Best AP at IoU 0.5

  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: True
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs
    log_freq: 50  # Log every 50 batches (less verbose)


# ============================================================================
# Launcher Configuration
# ============================================================================

launcher:
  num_nodes: 1
  gpus_per_node: 2  # 2x RTX 3090
  experiment_log_dir: ${paths.experiment_log_dir}
  multiprocessing_context: spawn  # Required for Windows

submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 72
  use_cluster: False  # Local training
  cpus_per_task: 8
  port_range: [29500, 29600]  # Narrow range to avoid Windows reserved ports
  constraint: null
